<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.example</groupId>
    <artifactId>ORIS2_403</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>pom</packaging>
    <modules>
        <module>lab2_4_spring_jpa</module>
        <module>lab2_5_spring_security</module>
        <module>lab2_1_embedded_tomcat</module>
        <module>lab2_2_spring_context_em</module>
        <module>lab2_3_jpa</module>
        <module>lab2_6_spring_security_jwt</module>
        <module>lab2_2_HW</module>
        <module>lab2_2_spring_hw</module>
        <module>lab2_8_nats</module>
        <module>lab8-nats-publisher</module>
        <module>lab2_9_inner_service</module>
    </modules>

    <properties>
        <maven.compiler.source>25</maven.compiler.source>
        <maven.compiler.target>25</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

</project>